from .. import statics as statics
from gremlin_python.process.graph_traversal import GraphTraversalSource as GraphTraversalSource
from gremlin_python.process.traversal import TraversalStrategies as TraversalStrategies
from gremlin_python.structure.graph import Graph as Graph
from typing import Any

class AnonymousTraversalSource:
    traversal_source_class: Any = ...
    def __init__(self, traversal_source_class: Any = ...) -> None: ...
    @classmethod
    def traversal(cls, traversal_source_class: Any = ...): ...
    def withGraph(self, graph: Any): ...
    def withRemote(self, remote_connection: Any): ...

def traversal(traversal_source_class: Any = ...): ...
