"""
This type stub file was generated by pyright.
"""

def random_sample(random=...):
    ...

def cumsum(it):
    ...

def choices_distribution_unique(a, p, random=..., length=...):
    ...

def choices_distribution(a, p, random=..., length=...):
    ...

