"""
This type stub file was generated by pyright.
"""

def get_path(module):
    ...

def list_module(module):
    ...

def find_available_locales(providers):
    ...

def find_available_providers(modules):
    ...

