from gremlin_python.driver import connection as connection, protocol as protocol, request as request, serializer as serializer, resultset
from gremlin_python.process import traversal as traversal
from typing import Any, Optional

class Client:
    def __init__(self, url: str, traversal_source: str, protocol_factory: Optional[Any] = ..., transport_factory: Optional[Any] = ..., pool_size: Optional[Any] = ..., max_workers: Optional[Any] = ..., message_serializer: Optional[Any] = ..., username: str = ..., password: str = ..., headers: Optional[Any] = ...): ...
    @property
    def available_pool_size(self): ...
    @property
    def executor(self): ...
    @property
    def traversal_source(self): ...
    def close(self) -> None: ...
    def submit(self, message: Any, bindings: Optional[Any] = ...) -> resultset.ResultSet: ...
    def submitAsync(self, message: Any, bindings: Optional[Any] = ...): ...
