from gremlin_python.driver import resultset as resultset
from typing import Any, Optional

class Connection:
    def __init__(self, url: Any, traversal_source: Any, protocol: Any, transport_factory: Any, executor: Any, pool: Any, headers: Optional[Any] = ...) -> None: ...
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def write(self, request_message: Any): ...
