"""
This type stub file was generated by pyright.
"""

from .base import BaseTest

class AssertionProxy(BaseTest):
    """
    AssertionProxy is used as proxy delegator call chain for test
    definitions.
    """
    def __init__(self, resolver, operator, fn) -> None:
        ...
    
    def __call__(self, expected, *args, **kw):
        ...
    
    def is_on_access(self):
        ...
    
    def __getattr__(self, name):
        """
        Overloads attribute accessor in order to load the assertion
        operator dynamically.
        """
        ...
    
    def __ror__(self, value):
        """
        Overloads ``|`` operator.
        """
        ...
    
    def __gt__(self, value) -> bool:
        """
        Overloads ``>`` operator.
        """
        ...
    


