"""
This type stub file was generated by pyright.
"""

unsupported_operators = (('rshit', '>>'), ('lshift', '<<'), ('add', '+'), ('and', '&'))
def not_implemented(symbol, self, value):
    """
    Raises an `NotImplementedError` exception when called.
    """
    ...

class BaseTest(object):
    """
    BaseTest implements magic method that explicitly raises an exception
    if consumed with unsupported binary operators.

    Note: methods are defined dynamically. See below.
    """
    ...


