"""
This type stub file was generated by pyright.
"""

def validate(method):
    """
    Config option name value validator decorator.
    """
    ...

class Config(object):
    """
    Config provides a simple key-value Pythonic data store for grappa
    runtime configuration settings.
    """
    defaults = ...
    allowed_opts = ...
    def __init__(self) -> None:
        ...
    
    @validate
    def __getattr__(self, name):
        ...
    
    @validate
    def __setattr__(self, name, value):
        ...
    


config = Config()
