"""
This type stub file was generated by pyright.
"""

class Empty(object):
    """
    Empty object represents emptyness state in `grappa`.
    """
    def __repr__(self):
        ...
    
    def __len__(self):
        ...
    


empty = Empty()
