"""
This type stub file was generated by pyright.
"""

def isoperator(x):
    """
    Returns `True` if the given object implements the required attributes for
    an operator.

    Returns:
        bool
    """
    ...

def register_operators(*operators):
    """
    Registers one or multiple operators in the test engine.
    """
    ...

class Engine(object):
    """
    Engine implements the test engine responsible of registering, storing and
    running test operators.
    """
    operators = ...
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def register(*operators):
        """
        Registers one or multiple operators in the test engine.
        """
        ...
    
    @property
    def empty(self):
        ...
    
    def add_assertion(self, assertion):
        ...
    
    def add_keyword(self, keyword):
        ...
    
    def reverse(self):
        ...
    
    def find_operator(self, name):
        ...
    
    def run(self, ctx):
        ...
    
    def reset(self):
        ...
    
    def reset_keywords(self):
        ...
    
    def clone(self):
        ...
    


