"""
This type stub file was generated by pyright.
"""

import sys
import logging
from colorama import Fore, Style

log = logging.getLogger('grappa')
formatter = logging.Formatter(u'{}=>{} {}[grappa]{} {}%(asctime)s{} | %(message)s'.format(Fore.GREEN, Style.RESET_ALL, Fore.MAGENTA, Style.RESET_ALL, Fore.CYAN, Style.RESET_ALL))
handler = logging.StreamHandler(sys.stdout)
