"""
This type stub file was generated by pyright.
"""

class Message(object):
    def __init__(self, allowance=..., negation=...) -> None:
        ...
    
    def render(self, negation=...):
        ...
    


class Description(object):
    ARROW = ...
    def __init__(self, *text) -> None:
        ...
    
    def render(self, separator):
        ...
    


class Reference(object):
    TOKEN = ...
    TEXT = ...
    def __init__(self, url=...) -> None:
        ...
    
    def render(self, separator):
        ...
    


class Help(object):
    def __init__(self, description=..., *references) -> None:
        ...
    
    def render(self, separator):
        ...
    


