"""
This type stub file was generated by pyright.
"""

class ErrorReporter(object):
    """
    ErrorReporter renders a given assertion error based on the
    built-in error reporters.
    """
    def __init__(self, ctx) -> None:
        ...
    
    def render_reporters(self, template, error):
        ...
    
    def run(self, error):
        ...
    


