"""
This type stub file was generated by pyright.
"""

class ErrorTemplate(object):
    """
    ErrorTemplate is used to compose and render a human-friendly
    descriptive error message.
    """
    separator = ...
    section_separator = ...
    header = ...
    def __init__(self) -> None:
        ...
    
    @property
    def color(self):
        ...
    
    @property
    def reset(self):
        ...
    
    def map_iterable(self, content):
        ...
    
    def block(self, title, content):
        ...
    
    def render(self):
        ...
    


