from .test import Test

"""
This type stub file was generated by pyright.
"""


class TestProxy(object):
    """
    TestProxy acts like a delegator intermediate proxy between public
    API calls and `Test` instances defining the test style.

    Arguments:
        style (str): test style between `should` or `expect`.
    """

    def __init__(self, style) -> None:
        ...

    def __getattr__(self, name):
        """
        Overloads object attribute accessory proxy to the currently used
        operator and parent test instance.
        """
        ...

    def __call__(self, *args, **kw):
        """
        Makes proxy object itself callable, delegating the invokation
        to a new test instance.
        """
        ...

    @property
    def be(self) -> Test:
        ...
