"""
This type stub file was generated by pyright.
"""

class getargspec(object):
    def __init__(self, method) -> None:
        ...
    
    @property
    def args(self):
        ...
    
    @property
    def varargs(self):
        ...
    
    @property
    def varkw(self):
        ...
    
    @property
    def defaults(self):
        ...
    


