"""
This type stub file was generated by pyright.
"""

import logging
import sys

logger = logging.getLogger(__name__)
inREPL = bool(getattr(sys, 'ps1', False))
if inREPL:
    ...
else:
    ...
class Factory(object):
    @classmethod
    def create(cls, locale=..., providers=..., generator=..., includes=..., **config):
        ...
    


