"""
This type stub file was generated by pyright.
"""

import sys

PY2 = sys.version_info[0] == 2
PY3 = sys.version_info[0] == 3
if PY3:
    ...
else:
    def raise_from(value, from_value):
        ...
    
