"""
This type stub file was generated by pyright.
"""

def all_fn(*fs):
    """Constructs a predicate, which holds when all fs hold."""
    ...

def any_fn(*fs):
    """Constructs a predicate, which holds when any fs holds."""
    ...

def none_fn(*fs):
    """Constructs a predicate, which holds when none of fs hold."""
    ...

def one_fn(*fs):
    """Constructs a predicate, which holds when exactly one of fs holds."""
    ...

def some_fn(*fs):
    """Constructs a function, which calls fs one by one
       and returns first truthy result."""
    ...

