"""
This type stub file was generated by pyright.
"""

class EmptyType:
    def __repr__(self):
        ...
    


EMPTY = EmptyType()
def isnone(x):
    ...

def notnone(x):
    ...

def inc(x):
    ...

def dec(x):
    ...

def even(x):
    ...

def odd(x):
    ...

