"""
This type stub file was generated by pyright.
"""

import sys
from .py3 import *

"""
Rewrite function names to represent Python 2 list-by-default interface.
Iterator versions go with i prefix.
"""
RENAMES = {  }
py2 = sys.modules[__name__]
