"""
This type stub file was generated by pyright.
"""

from .calc import *
from .colls import *
from .tree import *
from .decorators import *
from .funcolls import *
from .funcs import *
from .seqs import *
from .types import *
from .strings import *
from .flow import *
from .objects import *
from .debug import *
from .primitives import *
from .compat import PY3

modules = ('calc', 'colls', 'tree', 'decorators', 'funcolls', 'funcs', 'seqs', 'types', 'strings', 'flow', 'objects', 'debug', 'primitives')
if PY3:
    def lzip(*seqs):
        """List zip() version."""
        ...
    
else:
    lzip = zip
