"""
This type stub file was generated by pyright.
"""

import re

_re_type = type(re.compile(r''))
def re_iter(regex, s, flags=...):
    """Iterates over matches of regex in s, presents them in simplest possible form"""
    ...

def re_all(regex, s, flags=...):
    """Lists all matches of regex in s, presents them in simplest possible form"""
    ...

def re_find(regex, s, flags=...):
    """Matches regex against the given string,
       returns the match in the simplest possible form."""
    ...

def re_test(regex, s, flags=...):
    """Tests whether regex matches against s."""
    ...

def re_finder(regex, flags=...):
    """Creates a function finding regex in passed string."""
    ...

def re_tester(regex, flags=...):
    """Creates a predicate testing passed string with regex."""
    ...

def str_join(sep, seq=...):
    """Joins the given sequence with sep.
       Forces stringification of seq items."""
    ...

def cut_prefix(s, prefix):
    """Cuts prefix from given string if it's present."""
    ...

def cut_suffix(s, suffix):
    """Cuts suffix from given string if it's present."""
    ...

