"""
This type stub file was generated by pyright.
"""

def tree_leaves(root, follow=..., children=...):
    """Iterates over tree leaves."""
    ...

def ltree_leaves(root, follow=..., children=...):
    """Lists tree leaves."""
    ...

def tree_nodes(root, follow=..., children=...):
    """Iterates over all tree nodes."""
    ...

def ltree_nodes(root, follow=..., children=...):
    """Lists all tree nodes."""
    ...

