"""
This type stub file was generated by pyright.
"""

from .compat import Iterable, Iterator, Mapping, Sequence, Set, range

def isa(*types):
    """
    Creates a function checking if its argument
    is of any of given types.
    """
    ...

is_mapping = isa(Mapping)
is_set = isa(Set)
is_seq = isa(Sequence)
is_list = isa(list)
is_tuple = isa(tuple)
is_seqcoll = isa(list, tuple)
is_seqcont = isa(list, tuple, Iterator, range)
iterable = isa(Iterable)
is_iter = isa(Iterator)
