"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import, division, print_function

"""The Tornado web server and tools."""
version = "5.1.1"
version_info = (5, 1, 1, 0)
