"""
This type stub file was generated by pyright.
"""

import logging
from tornado.httpclient import AsyncHTTPClient, HTTPError

"""Non-blocking HTTP client implementation using pycurl."""
curl_log = logging.getLogger('tornado.curl_httpclient')
class CurlAsyncHTTPClient(AsyncHTTPClient):
    def initialize(self, max_clients=..., defaults=...):
        ...
    
    def close(self):
        ...
    
    def fetch_impl(self, request, callback):
        ...
    
    def handle_callback_exception(self, callback):
        ...
    


class CurlError(HTTPError):
    def __init__(self, errno, message) -> None:
        ...
    


if __name__ == "__main__":
    ...
