"""
This type stub file was generated by pyright.
"""

import pprint
from six.moves import reprlib

class SafeRepr(reprlib.Repr):
    """subclass of repr.Repr that limits the resulting size of repr()
    and includes information on exceptions raised during the call.
    """
    def repr(self, x):
        ...
    
    def repr_unicode(self, x, level):
        ...
    
    def repr_instance(self, x, level):
        ...
    


def safeformat(obj):
    """return a pretty printed string for the given object.
    Failing __repr__ functions of user instances will be represented
    with a short exception info.
    """
    ...

def saferepr(obj, maxsize=...):
    """return a size-limited safe repr-string for the given object.
    Failing __repr__ functions of user instances will be represented
    with a short exception info and 'saferepr' generally takes
    care to never raise exceptions itself.  This function is a wrapper
    around the Repr/reprlib functionality of the standard 2.6 lib.
    """
    ...

