"""
This type stub file was generated by pyright.
"""

from .decorators import immutable, mutable, serializer
from .types import ImmutableDict, TypedMapping, TypedSequence, TypedSet
from .fields import BooleanField, ChildField, DateField, DateTimeField, DecimalField, FloatField, IntegerField, MappingField, RegexField, SequenceField, SetField, StringField, TimeField, URLField, UUIDField
from .functions import from_json, from_yaml, is_model, to_dict, to_json, to_model, to_yaml
from . import dispatchers

__author__ = """Ian Maurer"""
__email__ = 'ian@genomoncology.com'
__version__ = '0.7.2'
__uri__ = "http://www.github.com/genomoncology/related"
__copyright__ = "Copyright (c) 2017 genomoncology.com"
__description__ = "Related: Straightforward nested object models in Python"
__doc__ = __description__ + " <" + __uri__ + ">"
__license__ = "MIT"
__title__ = "related"
