"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, TypeVar

_C = TypeVar("_C", bound=type)


def mutable(maybe_cls: Any = ..., strict: bool = ...) -> Callable[[_C], _C]:
    ...


def immutable(maybe_cls: Any = ..., strict: bool = ...) -> Callable[[_C], _C]:
    ...


def serializer(func=..., **kwargs):
    ...
