"""
This type stub file was generated by pyright.
"""


from typing import Any


def mutable(maybe_cls: Any = ..., strict: bool = ...) -> Any:
    ...


def immutable(maybe_cls: Any = ..., strict: bool = ...) -> Any:
    ...


def serializer(func=..., **kwargs):
    ...
