"""
This type stub file was generated by pyright.
"""

from decimal import Decimal
from future.moves.urllib.parse import ParseResult
from enum import Enum
from uuid import UUID
from datetime import date, datetime, time
from .functions import to_dict
from .types import TypedMapping, TypedSequence, TypedSet

@to_dict.register(list)
@to_dict.register(set)
@to_dict.register(tuple)
def _(obj, **kwargs):
    ...

@to_dict.register(dict)
def _(obj, **kwargs):
    ...

@to_dict.register(TypedSequence)
def _(obj, **kwargs):
    ...

@to_dict.register(TypedSet)
def _(obj, **kwargs):
    ...

@to_dict.register(TypedMapping)
def _(obj, **kwargs):
    ...

@to_dict.register(Enum)
def _(obj, **kwargs):
    ...

@to_dict.register(UUID)
def _(obj, **kwargs):
    ...

@to_dict.register(ParseResult)
def _(obj, **kwargs):
    ...

@to_dict.register(date)
def _(obj, **kwargs):
    ...

@to_dict.register(datetime)
def _(obj, **kwargs):
    ...

@to_dict.register(time)
def _(obj, **kwargs):
    ...

@to_dict.register(Decimal)
def _(obj, **kwargs):
    ...

