"""
This type stub file was generated by pyright.
"""

from attr import attributes

@attributes(repr=False, slots=True)
class _CompositeValidator(object):
    validators = ...
    def __call__(self, inst, attr, value):
        ...
    
    def __repr__(self):
        ...
    


def composite(*validators):
    """A validator that executes each validator passed as arguments.
    """
    ...

@attributes(repr=False, slots=True)
class _RegexValidator(object):
    regex = ...
    def __call__(self, inst, attr, value):
        ...
    
    def __repr__(self):
        ...
    


def regex(match_string):
    """A validator that executes each validator passed as arguments.

    """
    ...

