"""
This type stub file was generated by pyright.
"""

import pprint
import six
import _pytest._code
from __future__ import absolute_import, division, print_function
from ..compat import Sequence
from _pytest import outcomes
from _pytest._io.saferepr import saferepr
from _pytest.compat import ATTRS_EQ_FIELD

"""Utilities for assertion debugging"""
_reprcompare = None
def ecu(s):
    ...

def format_explanation(explanation):
    """This formats an explanation

    Normally all embedded newlines are escaped, however there are
    three exceptions: \n{, \n} and \n~.  The first two are intended
    cover nested explanations, see function and attribute explanations
    for examples (.visit_Call(), visit_Attribute()).  The last one is
    for when one explanation needs to span multiple lines, e.g. when
    displaying diffs.
    """
    ...

def issequence(x):
    ...

def istext(x):
    ...

def isdict(x):
    ...

def isset(x):
    ...

def isdatacls(obj):
    ...

def isattrs(obj):
    ...

def isiterable(obj):
    ...

def assertrepr_compare(config, op, left, right):
    """Return specialised explanations for some operators/operands"""
    ...

