"""
This type stub file was generated by pyright.
"""

from ..engine import Engine

operators = (('attributes', ), ('type', 'TypeOperator'), ('none', 'NoneOperator'), ('keys', 'KeysOperator'), ('index', 'IndexOperator'), ('match', 'MatchOperator'), ('length', 'LengthOperator'), ('empty', 'EmptyOperator'), ('equal', 'EqualOperator'), ('within', 'WithinOperator'), ('present', 'PresentOperator'), ('contain', 'ContainOperator'), ('only', 'ContainOnlyOperator'), ('callable', 'CallableOperator'), ('property', 'PropertyOperator'), ('pass_test', 'PassTestOperator'), ('implements', 'ImplementsOperator'), ('raises', 'RaisesOperator'), ('bool', 'TrueOperator', 'FalseOperator'), ('start_end', 'StartWithOperator', 'EndWithOperator'), ('range', 'BelowOperator', 'AboveOperator', 'AboveOrEqualOperator', 'BelowOrEqualOperator'))
def load():
    """
    Loads the built-in operators into the global test engine.
    """
    ...

