"""
This type stub file was generated by pyright.
"""

import sys
import traceback
import _pytest._code
import pytest
from __future__ import absolute_import, division, print_function
from _pytest.compat import getimfunc
from _pytest.config import hookimpl
from _pytest.outcomes import fail, skip, xfail
from _pytest.python import Class, Function

""" discovery and running of std-library "unittest" style tests. """
def pytest_pycollect_makeitem(collector, name, obj):
    ...

class UnitTestCase(Class):
    nofuncargs = ...
    def collect(self):
        ...
    


class TestCaseFunction(Function):
    nofuncargs = ...
    _excinfo = ...
    _testcase = ...
    def setup(self):
        ...
    
    def teardown(self):
        ...
    
    def startTest(self, testcase):
        ...
    
    def addError(self, testcase, rawexcinfo):
        ...
    
    def addFailure(self, testcase, rawexcinfo):
        ...
    
    def addSkip(self, testcase, reason):
        ...
    
    def addExpectedFailure(self, testcase, rawexcinfo, reason=...):
        ...
    
    def addUnexpectedSuccess(self, testcase, reason=...):
        ...
    
    def addSuccess(self, testcase):
        ...
    
    def stopTest(self, testcase):
        ...
    
    def runtest(self):
        ...
    


@hookimpl(tryfirst=True)
def pytest_runtest_makereport(item, call):
    ...

@hookimpl(hookwrapper=True)
def pytest_runtest_protocol(item):
    ...

def check_testcase_implements_trial_reporter(done=...):
    ...

