"""
This type stub file was generated by pyright.
"""

import os

"""Implementation of platform-specific functionality.

For each function or class described in `tornado.platform.interface`,
the appropriate platform-specific implementation exists in this module.
Most code that needs access to this functionality should do e.g.::

    from tornado.platform.auto import set_close_exec
"""
if 'APPENGINE_RUNTIME' in os.environ:
    def set_close_exec(fd):
        ...
    
else:
    ...
