"""
This type stub file was generated by pyright.
"""

from tornado.platform import interface

"""Lowest-common-denominator implementations of platform functionality."""
def try_close(f):
    ...

class Waker(interface.Waker):
    """Create an OS independent asynchronous pipe.

    For use on platforms that don't have os.pipe() (or where pipes cannot
    be passed to select()), but do have sockets.  This includes Windows
    and Jython.
    """
    def __init__(self) -> None:
        ...
    
    def fileno(self):
        ...
    
    def write_fileno(self):
        ...
    
    def wake(self):
        ...
    
    def consume(self):
        ...
    
    def close(self):
        ...
    


