"""
This type stub file was generated by pyright.
"""

from tornado.ioloop import PollIOLoop

"""EPoll-based IOLoop implementation for Linux systems."""
class EPollIOLoop(PollIOLoop):
    def initialize(self, **kwargs):
        ...
    


