"""
This type stub file was generated by pyright.
"""

from tornado.ioloop import PollIOLoop

"""KQueue-based IOLoop implementation for BSD/Mac systems."""
class _KQueue(object):
    """A kqueue-based event loop for BSD/Mac systems."""
    def __init__(self) -> None:
        ...
    
    def fileno(self):
        ...
    
    def close(self):
        ...
    
    def register(self, fd, events):
        ...
    
    def modify(self, fd, events):
        ...
    
    def unregister(self, fd):
        ...
    
    def poll(self, timeout):
        ...
    


class KQueueIOLoop(PollIOLoop):
    def initialize(self, **kwargs):
        ...
    


