"""
This type stub file was generated by pyright.
"""

from tornado.ioloop import PollIOLoop

"""Select-based IOLoop implementation.

Used as a fallback for systems that don't support epoll or kqueue.
"""
class _Select(object):
    """A simple, select()-based IOLoop implementation for non-Linux systems"""
    def __init__(self) -> None:
        ...
    
    def close(self):
        ...
    
    def register(self, fd, events):
        ...
    
    def modify(self, fd, events):
        ...
    
    def unregister(self, fd):
        ...
    
    def poll(self, timeout):
        ...
    


class SelectIOLoop(PollIOLoop):
    def initialize(self, **kwargs):
        ...
    


