"""
This type stub file was generated by pyright.
"""

from .base import BaseReporter

class DiffReporter(BaseReporter):
    """
    Outputs the comparison differences result between the
    subject/expected objects.
    """
    title = ...
    def run(self, error):
        ...
    


