"""
This type stub file was generated by pyright.
"""

from .base import BaseReporter

class UnexpectedError(BaseReporter):
    title = ...
    default_reasons = ...
    def run(self, error):
        ...
    


