"""
This type stub file was generated by pyright.
"""

from .base import BaseReporter

class SubjectMessageReporter(BaseReporter):
    title = ...
    attribute = ...
    def run(self, error):
        ...
    


