from gremlin_python.driver.transport import AbstractBaseTransport as AbstractBaseTransport
from typing import Any, Optional

class TornadoTransport(AbstractBaseTransport):
    def __init__(self) -> None: ...
    def connect(self, url: Any, headers: Optional[Any] = ...): ...
    def write(self, message: Any): ...
    def read(self): ...
    def close(self) -> None: ...
    def closed(self): ...
